name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Initialize and update submodules
        run: git submodule update --init --recursive
      - name: Set up CMake
        run: sudo apt-get install -y cmake
      - name: Build
        run: |
          cmake -Bbuild -S.  # Generate build files in a separate directory
          cmake --build build --config Release
      - name: Run tests
        run: |
          cd build
          ./tests
